ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
