ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
