ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
