ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_oem/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
